name: Lint & Format

on:
    pull_request:
        branches: [master, dev]

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 26
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Formatting check
              run: pnpm run format:check
